### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [droplet-editor/droplet#229]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

*Is there anything I can do to help this community, this open project?*

**Comment by ghost** [comment]
Seems like the project is dead, my friend, what a shame. I tried to install it, and it's complicated. It's full of dependency conflicts, and I must mention that the main branch hasn't been updated in 7 years. It makes me want to cry. It would be great to create an alternative project (although it will be very challenging) that can gain momentum. Let's hope that happens. Greetings!

**Comment by doctorjei** [comment]
Hi all - while I don't expect much new development here (I want to merge some old fixes), I am working on a new editor here:
https://github.com/cacticouncil/lilypad

**Comment by ghost** [comment]
> Hi all - while I don't expect much new development here (I want to merge some old fixes), I am working on a new editor here: https://github.com/cacticouncil/lilypad

Cool! Is lilypad editor similar to Droplet?

**Comment by doctorjei** [comment]
@chipacu - feel free to email me (jjb@eng.ufl.edu) and I can send you a draft whitepaper about it.
